config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :users, controllers:{
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get '/charities/listings', to: 'charities#listings'
  post '/charities/new', to: 'charities#create'

  resources :conversations do
    resources :messages
  end
  
  resources :line_items
  resources :carts
  resources :charities

  get '/volunteers/listings', to: 'volunteers#listings'

  resources :organizations
  resources :volunteers

  get "/payments/success", to: "payments#success"


  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/charity.rb
class Charity < ApplicationRecord
 
  # before_destroy :not_referenced_by_any_line_item
  belongs_to :category
  belongs_to :organization
  has_many :line_items, dependent: :destroy
  
  has_many_attached :pictures

  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :summary, :challenges, :solution,  presence: true, length: { minimum: 10, maximum: 1000 }

private
  def not_refereced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, "Line items present")
      throw :abort
    end
  end


end

app/controllers/charities_controller.rb
class CharitiesController < ApplicationController

  before_action :set_charity, only:[:edit, :update, :show, :destroy]
  before_action :authenticate_user!, :except => [:listings, :show]

  def listings

    # add search function  
  
    if(params.has_key?(:search))
      @charities = Charity.where(["summary LIKE ?","%#{params[:search]}%"]).paginate(page: params[:page],per_page:6)
    else
      @charities = Charity.paginate(page: params[:page],per_page:6)

    end
   # add sort function  
    if (params.has_key?(:location))
      @charities = Charity.where(location:params[:location]).paginate(page: params[:page],per_page:3)
  
    end
   # add filter function  
    if (params.has_key?(:category))
      @charities = Charity.where(category:params[:category]).paginate(page: params[:page],per_page:3)
    end

  end

  # show the current organization's projects
  def index
    @charities=current_user.organization.charities.paginate(page: params[:page],per_page:6)
  end

   
  def new
    @charity=Charity.new

  end


  def create
    @charity=current_user.organization.charities.create(charity_params)
    if @charity.save
        redirect_to charity_path(@charity)
    else
        render 'new'
    end 
  end

  

  def edit
    # only allows user to access the edit page of his own listings
    @charity = Charity.find(params[:id])
    if current_user.admin?
      
    elsif current_user.id != @charity.organization.user_id 
        redirect_to root_path
    end
  end

  def update
    if @charity.update(charity_params)
      
      redirect_to charity_path(@charity)
    else
      render 'edit'
    end
  end

  def show

    @charities = Charity.order("created_at ASC").limit(2)
    
  end

  def destroy
    @charity.destroy
    redirect_to charities_path
  end

  private

    def set_charity
      @charity = Charity.find(params[:id])
    end

    def charity_params
      params.require(:charity).permit(:title,:location, :project_leader, :category_id,:raised_goal, :current_raised, :summary, :challenges,:solution, :donate_basic, pictures: [])
    end

end

app/helpers/charities_helper.rb
module CharitiesHelper
end

app/views/charities/edit.html.erb
<%=render 'errors/error', obj: @charity%>
<div class="section-charity">
  <div class="row ">
    <div class="col-md-6  mx-auto clear-padding-col clear-padding-row">
      <div class="image-charity">  
      </div>
      
    </div>
    <div class="col-md-6  mx-auto clear-col">
      <div class="charity-infor">
        <h2 class="edit">Update Your project</h2>

        <%= form_with(model: @charity, local: true) do |form| %>
         
            <div class="form-group">
                <%= form.label :Title , class:'charity-label'%><br />
                <%= form.text_field :title, autofocus: true, autocomplete: "Enter you name",class:"form-control" %>
              
            </div>

            <div class="field">
                <%= form.label :Location , class:'charity-lable'%><br />
                <%= form.text_area :location, autofocus: true, autocomplete: "Description",class:"form-control" %>
            </div>

            <div class="form-group">
                <%= form.label :project_leader , class:'charity-lable'%><br />
                <%= form.text_area :project_leader, autofocus: true, autocomplete: "project_leader",class:"form-control" %>
            </div>

            <div class="form-group">
                <%= form.label :category , class:'charity-lable'%><br />
                <%= form.select :category_id , options_for_select(Category.all.collect{|u| [u.title,u.id]}) %>
            </div>
            

            <div class="form-group">
                <%= form.label :'raised of goal' , class:'charity-lable'%>
                 <div class="input-group">
                    <div class="input-group-addon">AUD</div>
                    <%= form.number_field :raised_goal, autofocus: true, class:"form-control", id:"exampleInputAmount"  %>
                </div>
            </div>
           

            <div class="form-group">
                <%= form.label :current_raised , class:'charity-lable'%>
                 <div class="input-group">
                    <div class="input-group-addon">AUD</div>
                    <%= form.number_field :current_raised, autofocus: true, class:"form-control", id:"exampleInputAmount"  %>
                </div>
            </div>

            <div class="form-group">
              <%= form.label :summary , class:'charity-lable'%><br />
                <%= form.text_area :summary, autofocus: true, autocomplete: "current_raised",class:"form-control" %>
            </div>
            <div class="form-group">
              <%= form.label :Challenges , class:'charity-lable'%><br />
                <%= form.text_area :challenges, autofocus: true, autocomplete: "current_raised",class:"form-control" %>
            </div>
            <div class="form-group">
              <%= form.label :Solution , class:'charity-lable'%><br />
                <%= form.text_area :Solution, autofocus: true, autocomplete: "current_raised",class:"form-control" %>
            </div>
            <div class="form-group">
              <%= form.label :donate_basic , class:'charity-lable'%><br />
                <%= form.text_area :donate_basic, autofocus: true, autocomplete: "current_raised",class:"form-control" %>
            </div>

             <div>
                 <%= form.file_field :pictures, accept:
                     'image/png,image/gif,image/jpeg,image/jpg',multiple: true %>
            </div>

            <div>
                <%= form.submit "Update",class:'charity-submit'%>
            </div>

        <% end %>

      </div>
    </div>    
  </div>
</div>

app/views/charities/index.html.erb
<div class="section-listings">

    <div class="image-charity">

    
    </div>

    <div class="container">
      <h2>All Projects</h2>

      <div class="all-projects">
      
        <section>
          <div class="container">
          <div class="row">
            <% if @charities !=nil %>
              <% @charities.each do |charity| %>
                  <div class="col-md-4  col-sm-auto listing-row">
                    <% charity.pictures.each do |picture| %>
                        <%= image_tag picture, class:"listing-picture" %>
                        <% break %>
                    <% end %>


                  
                    <div class="project-infor">
                      <div class="title-top">
                        <h3 class="category"><%= charity.category.title %></h3>
                        <%= link_to charity.title , charity_path(charity), class:"title" %>
                      </div>
                      
                      <div class="content">

                        <div class="top-summary">
                          <p><%= charity.summary.truncate(150) %></p>
                        </div>
                       
                        <div class="progress">
                          <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100" style="min-width: 1em; width: <%=((charity.current_raised).to_f/(charity.raised_goal).to_f) *100.0%>%;">
                            
                          </div>
                        </div>
                      </div>

                      <div class="raised">
                        <span>Raised: $ <span class="raised-number"><%= charity.current_raised %></span></span>
                        <span>Goal: $ <span class="raised-number"> <%= charity.raised_goal %></span></span>
                      </div>
                    </div>  

                    <% if user_signed_in? && current_user.admin? || current_user.organization != nil %>
                      <div class="button">
                        <button class="edit-button"><%= link_to 'Edit', edit_charity_path(charity),class:"edit" %></button>
                        <button class="delete-button"><%= link_to 'Delete', charity_path(charity), method: :delete, data: { confirm: 'Are you sure?' },class:"delete"%></button>
                      
                      </div>
                    <% end %>  
                  </div> 
                <%end%>

 
            <% else %>
              <div>
                <h1>4004</h1>
                <h1>Page you are looking is not found</h1>
              </div>
            <% end %>
          </div>

          <div class="row">
            <div>
              <%= will_paginate %>
            </div>
          </div>

      
        </section>
      </div>

     
    
    </div>



</div>







  











 

app/views/charities/listings.html.erb
<div class="section-listings">

    <div class="image-charity ">

    
    </div>

    <div class="container">
      <h2>All Projects</h2>

      <div class="search-bar">
        <ul class="nav nav-pills">
            <li>
              <div class="row">
                <%= form_tag charities_listings_path, :method => 'get', class: 'input-group'  do %>
                  <%= text_field_tag :search, params[:search], class: 'form-control', placeholder: 'Search for...' %>
                  <span class="input-group-btn"><%= submit_tag "Search", class:"search-btn" %></span>
                <% end %>
              </div>
            </li>
            <li role="presentation" class="dropdown country">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                COUNTRY <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to 'India', charities_listings_path(location:"India") %></li>
                <li><%= link_to 'Kenya', charities_listings_path(location:"Kenya") %></li>
                <li><%= link_to 'Nepal', charities_listings_path(location:"Nepal") %></li>
                <li><%= link_to 'Mexico', charities_listings_path(location:"Mexico") %></li>
              
              </ul>
            </li>
            <li role="presentation" class="dropdown category">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                THEME <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Women and Girls', charities_listings_path(category: Category.find(1)) %></li>
                <li><%= link_to 'Education', charities_listings_path(category: Category.find(2)) %></li>
                <li><%= link_to 'Health', charities_listings_path(category: Category.find(3)) %></li>
                <li><%= link_to 'Environment', charities_listings_path(category: Category.find(4)) %></li>
                <li><%= link_to 'Hunger', charities_listings_path(category: Category.find(6)) %></li>
                <li><%= link_to 'Economic Development', charities_listings_path(category: Category.find(5)) %></li>
              </ul>
            </li>

            <li><%= link_to 'Clear All Filters', charities_listings_path,class:"all-projects" %></li>
          </ul>
      
      </div>

      <div class="all-projects">
      
        <section>
          <div class="container">
          <div class="row">
            <% if @charities !=nil %>
              <% @charities.each do |charity| %>
                  <div class="col-md-4  col-sm-auto listing-row">
                    <div class="hover-box">
                      <% charity.pictures.each do |picture| %>
                          <%= image_tag picture, class:"listing-picture" %>
                          <% break %>
                      <% end %>
                    
                    <div class="image-hover">

          
                     <%= link_to  'Donate Now', charity_path(charity), class:"donate-basic" %> 
                    </div>

                   </div>


                    <div class="project-infor infor-responsive">
                      <div class="title-top">
                        <h3 class="category"><%= charity.category.title %></h3>
                        <%= link_to charity.title , charity_path(charity), class:"title" %>
                      </div>
                      
                      <div class="content">

                        <div class="top-summary">
                          <p><%= charity.summary.truncate(150) %></p>
                        </div>
                       
                        <div class="progress">
                          <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100" style="min-width: 1em; width: <%=((charity.current_raised).to_f/(charity.raised_goal).to_f) *100.0%>%;">
                            
                          </div>
                        </div>
                      </div>

                      <div class="raised">
                        <span>Raised: $ <span class="raised-number"><%= charity.current_raised %></span></span>
                        <span>Goal: $ <span class="raised-number"> <%= charity.raised_goal %></span></span>
                      </div>

                      
                    </div> 
                    <% if user_signed_in? && current_user.admin?%>
                        <div class="button-listings">
                          <button class="edit-button"><%= link_to 'Edit', edit_charity_path(charity),class:"edit" %></button>
                          <button class="delete-button"><%= link_to 'Delete', charity_path(charity), method: :delete, class:"delete"%></button>
                        
                        </div>
                    <% end %>   
                  </div> 
                <%end%>

 
            <% else %>
              <div>
                <h1>4004</h1>
                <h1>Page you are looking is not found</h1>
              </div>
            <% end %>
          </div>

          <div class="row">
            <div>
              <%= will_paginate %>
            </div>
          </div>

      
        </section>
      </div>

     
    
    </div>



</div>







  











 

app/views/charities/new.html.erb
<%=render 'errors/error', obj: @charity%>
<div class="section-charity">
  <div class="row ">
    <div class="col-md-6  mx-auto clear-padding-col clear-padding-row">
      <div class="image-charity">  
      </div>
      
    </div>
    <div class="col-md-6  mx-auto clear-col">
      <div class="charity-infor">
        <h2>Welcome!</h2>
        
        <h3>Post A Project that Your Community Needs </h3>

        <%= form_with(model: @charity, local: true) do |form| %>
         
            <div class="form-group">
                <%= form.label :Title , class:'charity-label'%><br />
                <%= form.text_field :title, autofocus: true, autocomplete: "Enter you name",class:"form-control" ,placeholder:"Please enter your title (max 50 words)"%>
              
            </div>

            <div class="field">
                <%= form.label :Location , class:'charity-lable'%><br />
                <%= form.text_area :location, autofocus: true, autocomplete: "Description",class:"form-control" ,placeholder:"Please enter the project location" %>
            </div>

            <div class="form-group">
                <%= form.label :project_leader , class:'charity-lable'%><br />
                <%= form.text_area :project_leader, autofocus: true, autocomplete: "project_leader",class:"form-control",placeholder:"Please enter the leader name " %>
            </div>

            <div class="form-group">
                <%= form.label :category , class:'charity-lable'%><br />
                <%= form.select :category_id , options_for_select(Category.all.collect{|u| [u.title,u.id]}) %>
            </div>
            

            <div class="form-group">
                <%= form.label :'raised of goal' , class:'charity-lable'%>
                 <div class="input-group">
                    <div class="input-group-addon">AUD</div>
                    <%= form.number_field :raised_goal, autofocus: true, class:"form-control", id:"exampleInputAmount",placeholder:"Please enter the number 0-10,0000"   %>
                </div>
            </div>
           

            <div class="form-group">
                <%= form.label :current_raised , class:'charity-lable'%>
                 <div class="input-group">
                    <div class="input-group-addon">AUD</div>
                    <%= form.number_field :current_raised, autofocus: true, class:"form-control", id:"exampleInputAmount" ,placeholder:"Please enter the number 0-10,0000"  %>
                </div>
            </div>

            <div class="form-group">
              <%= form.label :summary , class:'charity-lable'%><br />
                <%= form.text_area :summary, autofocus: true, autocomplete: "current_raised",class:"form-control",placeholder:"Please enter your title (min 10 words)" %>
            </div>
            <div class="form-group">
              <%= form.label :Challenges , class:'charity-lable'%><br />
                <%= form.text_area :challenges, autofocus: true, autocomplete: "current_raised",class:"form-control",placeholder:"Please enter your title (min 10 words)" %>
            </div>
            <div class="form-group">
              <%= form.label :Solution , class:'charity-lable'%><br />
                <%= form.text_area :solution, autofocus: true, autocomplete: "current_raised",class:"form-control",placeholder:"Please enter your title (min 10 words)" %>
            </div>

            <div class="form-group">
                <%= form.label :donate_basic , class:'charity-lable'%>
                 <div class="input-group">
                    <div class="input-group-addon">AUD</div>
                    <%= form.number_field :donate_basic, autofocus: true, class:"form-control", id:"exampleInputAmount",placeholder:"Please enter the number 10-50"  %>
                </div>
            </div>


             <div>
                 <%= form.file_field :pictures, accept:
                     'image/png,image/gif,image/jpeg,image/jpg',multiple: true %>
            </div>

            <div>
                <%= form.submit "Submit",class:'charity-submit'%>
            </div>

        <% end %>

      </div>
    </div>    
  </div>
</div>

app/views/charities/show.html.erb
<div class="charity-show">

    <div class="show-image">
    
    </div>

    <div class="container">

     <h2 calss='chairty-title'><%= @charity.title %></h2>
     <h4 class="leader">Organizaed  by <%= @charity.project_leader %></h4>
        <div class="row">
            <div class="col-md-8 mx-auto clear-col">
                <% @charity.pictures.each do |picture| %>
                    <%= image_tag picture, class:"listing-picture" %>
                    <% break %>
                <% end %>

            </div>
            <div class="col-md-4 mx-auto clear-col">

                <div class="donate-box">
                    <%= button_to 'Donate Now', line_items_path(charity_id: @charity), class: 'add-cart is-warning add-to-cart' %> 
                 
                    <%= button_to 'Add to Donation Listing ', line_items_path(charity_id: @charity), class: 'add-cart is-warning add-to-cart' %>

                    <% if user_signed_in? && current_user.id != @charity.organization.user_id %>
                        <i class="fa fa-commenting" aria-hidden="true"></i>
                        <%= link_to "Messages", conversations_path(sender_id: current_user.id, recipient_id: @charity.organization.user_id), method: 'post', class:"message-button is-link" %>
                    <% elsif user_signed_in? && current_user.id == @charity.organization.user_id  %>
                        <i class="fa fa-commenting" aria-hidden="true"></i>
                        <%= link_to "Messages", conversations_path, class:"message-button2" %>
                    <% else %>
                        <%= link_to "Messages", user_session_path, class:"message-button2" %>
                    <% end %>
                </div>
                
                 <div class="organization">
                    <h4>Organization Information</h4>
                    <h3 class="org-title"><%=@charity.organization.title %></h3>
                    <p><%=@charity.organization.description %></p>
                 
                    <h3 class="location"><%=@charity.organization.location %></h3>
                </div>
            </div>

        </div>

        <div class="row">

            <div class="col-md-8 mx-auto clear-col">
            
                

                <div class="information-charity">
                    <div class="progress">
                        <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100" style="min-width: 1em; width: <%=((@charity.current_raised).to_f/(@charity.raised_goal).to_f) *100.0%>%;">
                        
                        </div>
                    </div>
                     <div class="raised-top">
                        <span>Raised: $ <span class="raised-number"><%= @charity.current_raised %></span></span>
                        <span>Goal: $ <span class="raised-number"> <%= @charity.raised_goal %></span></span>
                      </div>
                    <h2>summary</h2>
                    <h4><%= @charity.summary %></h4>
                    <h2>Challenges</h2>
                    <h4><%= @charity.challenges %></h4>
                    <h2>Solution</h2>
                    <h4><%= @charity.solution %></h4>
                </div>

            </div>  

            <div class="lasted-projects">
                <h2 calss="lasted">The Laste Projects</h2>
                <% @charities.each do |charity| %>
                    <div class="col-md-4  col-sm-auto listing-row">
                        <div class="hover-box2">
                            <% charity.pictures.each do |picture| %>
                                <%= image_tag picture, class:"listing-picture2" %>
                                <% break %>
                            <% end %>
                            
                            <div class="image-hover2">
                            <%= link_to  'Donate Now', charity_path(charity), class:"donate-basic" %> 
                            </div>
                        </div>


                        <div class="project-infor">
                            <div class="title-top2">
                                <h3 class="category"><%= charity.category.title %></h3>
                                <h3><%= link_to charity.title , charity_path(charity), class:"title" %></h3>
                            </div>

                            <div class="progress">
                            <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100" style="min-width: 1em; width: <%=((charity.current_raised).to_f/(charity.raised_goal).to_f) *100.0%>%;">
                                
                            </div>
                            </div>
                            
                    
                            <div class="raised">
                                <span>Raised: $ <span class="raised-number"><%= charity.current_raised %></span></span>
                                <span>Goal: $ <span class="raised-number"> <%= charity.raised_goal %></span></span>
                            </div>

                        </div>    
                    </div> 
                    <%end%>

            
            </div>


        </div>
    
    </div>


</div>




















    

   