config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :users, controllers:{
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get '/charities/listings', to: 'charities#listings'
  post '/charities/new', to: 'charities#create'

  resources :conversations do
    resources :messages
  end
  
  resources :line_items
  resources :carts
  resources :charities

  get '/volunteers/listings', to: 'volunteers#listings'

  resources :organizations
  resources :volunteers

  get "/payments/success", to: "payments#success"


  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def add_charity(charity)
    current_item = line_items.find_by(charity_id: charity.id)

    if current_item
      current_item.increment(:quantity)
    else
      current_item = line_items.build(charity_id: charity.id)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end

end

app/models/category.rb
class Category < ApplicationRecord

  has_many :charities
  
end

app/models/charity.rb
class Charity < ApplicationRecord
 
  # before_destroy :not_referenced_by_any_line_item
  belongs_to :category
  belongs_to :organization
  has_many :line_items, dependent: :destroy
  
  has_many_attached :pictures

  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :summary, :challenges, :solution,  presence: true, length: { minimum: 10, maximum: 1000 }

private
  def not_refereced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, "Line items present")
      throw :abort
    end
  end


end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, foreign_key: :sender_id, class_name: "User"
  belongs_to :recipient, foreign_key: :recipient_id, class_name: "User"

  has_many :messages

  validates_uniqueness_of :sender_id, scope: :recipient_id

  scope :between, -> (sender_id, recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id = ?) OR (conversations.sender_id = ? AND conversations.recipient_id = ?)", sender_id, recipient_id, recipient_id, sender_id)
  end
 
end

app/models/donor.rb
class Donor < ApplicationRecord
  belongs_to :user
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :charity
  belongs_to :cart

  def total_price
    charity.donate_basic.to_i * quantity.to_i
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user
  validates_presence_of :body, :conversation_id, :user_id

  def message_time
    created_at.strftime("%m/%d/%y at %l:%M %p")
  end
 
end

app/models/organization.rb
class Organization < ApplicationRecord

  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 1000 }
  validates_uniqueness_of :title, :website
  belongs_to :user
  has_many :charities
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :organization
  has_one :volunteer
  has_one :donor
 
end

app/models/volunteer.rb
class Volunteer < ApplicationRecord

  validates :name, presence: true, length: { minimum: 3, maximum: 20 }
  validates :description, presence: true, length: { minimum: 10, maximum: 1000 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 },
            uniqueness: { case_sensitive: false },
            format: { with: VALID_EMAIL_REGEX }

  belongs_to :user
  has_one_attached :picture
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

 
  def index
    @carts = Cart.all
  end

 
  def show
  # add the stripe payment in the cart show page
    @cart = Cart.find(params[:id])
    session = Stripe::Checkout::Session.create(
        payment_method_types: ['card'],
        customer_email: current_user.email,
        line_items: [{
            name: "Your donations",
            description: "description",
            amount: @cart.total_price * 100,
            currency: 'AUD',
            quantity: 1,
        }],
        payment_intent_data: {
            metadata: {
                user_id: current_user.id,
                cart_id: @cart.id
            }
        },
        success_url: "#{root_url}payments/success?userId=#{current_user.id}&cartId=#{@cart.id}",
        cancel_url: "#{root_url}listings"
    )

    @session_id = session.id
   

  end

 
  def new
    @cart = Cart.new
  end


  def edit
  end

 
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
   
    def set_cart
      @cart = Cart.find(params[:id])
    end

   
    def cart_params
      params.fetch(:cart, {})
    end

    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to root_path, notice: "That cart doesn't exist"
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :find_conversation

  def index
    @messages = @conversation.messages

    if @messages.length > 10
      @over_ten = true
      @messages = @messages[-10..-1]
    end

    if params[:m]
      @over_ten = false
      @messages = @conversation.messages
    end

    @message = @conversation.messages.new
  end

  def create
    @message = @conversation.messages.new(message_params)
    if @message.save
      redirect_to conversation_messages_path(@conversation)
    end
  end

  def new
    @message = @conversation.messages.new
  end




  private

    def message_params
      params.require(:message).permit(:body, :user_id)
    end

    def find_conversation
      @conversation = Conversation.find(params[:conversation_id])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def  home
  
  
  
  end


end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController

  skip_before_action :verify_authenticity_token, only: [:webhook]
  def success
   
    cart_id=params['cartId']
    @cart=Cart.find(cart_id)

    

  end

  def webhook
    payment_id =params[:data][:object][:payment_intent]
    payment =Stripe::PaymentIntent.retrieve(payment_id)

    listing_id =payment.metadata.listing.listing_id
    user_id =payment.metadata.user_id
    p "listing_id= " + listing_id
    p "user id =" + user_id
    p params
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def cart_count_over_one
    return total_cart_items if total_cart_items > 0
  end

  def total_cart_items
    total = @cart.line_items.map(&:quantity).sum
    return total if total > 0
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charities_helper.rb
module CharitiesHelper
end

app/helpers/chat_messages_helper.rb
module ChatMessagesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/volunteers_helper.rb
module VolunteersHelper
end

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<div class="cart-show">

  <div class="cart-image">
  
  </div>

    <div class="container">

      <div class="keep-donate">
        <%= link_to 'Keep Donating', charities_listings_path,class:"keep-button" %>

      </div>
      <hr>

      <div class="items">
       <%= render(@cart.line_items) %> <br>
      </div>

      <div class="payment">
        <div class="col-md-6">
          <%= button_to 'Empty Donating Listing', @cart, method: :delete, data: { confirm: "Are you sure? " }, class: "empty-button" %>
        </div>

        <div class="col-md-6">
          <div class="pay">
            <span class="total-price">Total: <%= number_to_currency(@cart.total_price) %></span>
            <button data-stripe="payment" class="payment-button">Go to Pay</button>
          </div>
         
        </div>

      </div>
    
    </div>
</div>





    <script src="https://js.stripe.com/v3/"></script>

    <script>
      document
        .querySelector("[data-stripe='payment']")
        .addEventListener("click", () => {
          const stripe = Stripe(
            "<%= Rails.application.credentials.dig(:stripe, :public_key) %>"
          );

          stripe.redirectToCheckout({
            sessionId: "<%= @session_id %>"
          });
        });
    </script>