config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :users, controllers:{
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get '/charities/listings', to: 'charities#listings'
  post '/charities/new', to: 'charities#create'

  resources :conversations do
    resources :messages
  end
  
  resources :line_items
  resources :carts
  resources :charities

  get '/volunteers/listings', to: 'volunteers#listings'

  resources :organizations
  resources :volunteers

  get "/payments/success", to: "payments#success"


  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def add_charity(charity)
    current_item = line_items.find_by(charity_id: charity.id)

    if current_item
      current_item.increment(:quantity)
    else
      current_item = line_items.build(charity_id: charity.id)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end

end

app/models/category.rb
class Category < ApplicationRecord

  has_many :charities
  
end

app/models/charity.rb
class Charity < ApplicationRecord
 
  # before_destroy :not_referenced_by_any_line_item
  belongs_to :category
  belongs_to :organization
  has_many :line_items, dependent: :destroy
  
  has_many_attached :pictures

  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :summary, :challenges, :solution,  presence: true, length: { minimum: 10, maximum: 1000 }

private
  def not_refereced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, "Line items present")
      throw :abort
    end
  end


end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, foreign_key: :sender_id, class_name: "User"
  belongs_to :recipient, foreign_key: :recipient_id, class_name: "User"

  has_many :messages

  validates_uniqueness_of :sender_id, scope: :recipient_id

  scope :between, -> (sender_id, recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id = ?) OR (conversations.sender_id = ? AND conversations.recipient_id = ?)", sender_id, recipient_id, recipient_id, sender_id)
  end
 
end

app/models/donor.rb
class Donor < ApplicationRecord
  belongs_to :user
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :charity
  belongs_to :cart

  def total_price
    charity.donate_basic.to_i * quantity.to_i
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user
  validates_presence_of :body, :conversation_id, :user_id

  def message_time
    created_at.strftime("%m/%d/%y at %l:%M %p")
  end
 
end

app/models/organization.rb
class Organization < ApplicationRecord

  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 1000 }
  validates_uniqueness_of :title, :website
  belongs_to :user
  has_many :charities
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :organization
  has_one :volunteer
  has_one :donor
 
end

app/models/volunteer.rb
class Volunteer < ApplicationRecord

  validates :name, presence: true, length: { minimum: 3, maximum: 20 }
  validates :description, presence: true, length: { minimum: 10, maximum: 1000 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 },
            uniqueness: { case_sensitive: false },
            format: { with: VALID_EMAIL_REGEX }

  belongs_to :user
  has_one_attached :picture
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

 
  def index
    @carts = Cart.all
  end

 
  def show
  # add the stripe payment in the cart show page
    @cart = Cart.find(params[:id])
    session = Stripe::Checkout::Session.create(
        payment_method_types: ['card'],
        customer_email: current_user.email,
        line_items: [{
            name: "Your donations",
            description: "description",
            amount: @cart.total_price * 100,
            currency: 'AUD',
            quantity: 1,
        }],
        payment_intent_data: {
            metadata: {
                user_id: current_user.id,
                cart_id: @cart.id
            }
        },
        success_url: "#{root_url}payments/success?userId=#{current_user.id}&cartId=#{@cart.id}",
        cancel_url: "#{root_url}listings"
    )

    @session_id = session.id
   

  end

 
  def new
    @cart = Cart.new
  end


  def edit
  end

 
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
   
    def set_cart
      @cart = Cart.find(params[:id])
    end

   
    def cart_params
      params.fetch(:cart, {})
    end

    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to root_path, notice: "That cart doesn't exist"
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def  home
  
  
  
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
  def cart_count_over_one
    return total_cart_items if total_cart_items > 0
  end

  def total_cart_items
    total = @cart.line_items.map(&:quantity).sum
    return total if total > 0
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charities_helper.rb
module CharitiesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/volunteers_helper.rb
module VolunteersHelper
end

app/views/layouts/_footer.html.erb
<footer>

  <div class="section">
    <div class="container">
      <div class="row">
        <div class="col-md-4 mx-auto box">
          <h4>About Us</h4>
          <p>Alienum phaedrum torquatos nec eu</p>
          
        </div>

        <div class="col-md-4 mx-auto box responsive">
          <h4>Call us <span>+615 4640 3304</span> </h4>
          <p>Visit us 2976 Washington St San Francisco</p>
        </div>
        <div class="col-md-4 mx-auto box responsive">
          <div class="icons">
            <i class="fa fa-facebook-official icon" aria-hidden="true"></i>
            <i class="fa fa-twitter-square icon" aria-hidden="true"></i>
            <i class="fa fa-linkedin-square icon" aria-hidden="true"></i>      
        </div>
        </div>
        
   
      </div>
      

    </div>

  </div>

</footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Good Giving', root_path, class:"navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      
        <li><%= link_to 'Explore Projects', charities_listings_path %></li>
        <li><%= link_to 'Meet Our Volunteers', volunteers_listings_path %></li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">

        <li>
          <% if total_cart_items %>
            <%= link_to cart_path(@cart), class:"navbar-item button is-warning" do %>
            <span class="icon is-small">
              <i class="fa fa-shopping-cart"></i>
            </span>
            <span>Cart
              <%= cart_count_over_one %>
            </span>
            <% end %>
          <% end %>
        </li>
        
    
      <% if user_signed_in? && current_user.user_type=="organization" %>
         <% if  current_user.organization !=nil && current_user.organization.title !=nil %>
         <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Welcome Back !<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Post a Project", new_charity_path%> </li> 
                <li role="separator" class="divider"></li>
              <li><%= link_to "All Projects", charities_path%> </li>
                <li role="separator" class="divider"></li> 
              <li><%= link_to "Edit Your Profile", edit_organization_path(current_user.organization) %> </li> 
                <li role="separator" class="divider"></li> 
              <li> <%= link_to "Messages", conversations_path %></li>
            </ul>
            <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %> </li> 
        </li>
        <% else %>
          <li> <%= link_to "Profile", organizations_path %></li>
          <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %> </li> 
        <% end %>
        

      <% elsif user_signed_in? && current_user.user_type=="volunteer"  %>
          <% if  current_user.volunteer !=nil && current_user.volunteer.name !=nil %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Profile<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Show your Profile", volunteer_path(current_user.volunteer)%> </li> 
                <li role="separator" class="divider"></li>
                <li><%= link_to "Edit your Profile", edit_volunteer_path(current_user.volunteer)%> </li>
                <li role="separator" class="divider"></li>
                <li> <%= link_to "Messages", conversations_path %></li>
              </ul>
            </li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %> </li> 

            <% else %>
              <li><%= link_to "Profile", volunteers_path %> </li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %> </li> 

            <% end %>
      <% elsif user_signed_in? && current_user.user_type=="donor" ||user_signed_in? && current_user.admin?  %>
        
        <li> <%= link_to "Messages", conversations_path %></li>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %> </li> 
      <% else%>
        <li><%= link_to 'Sign In', user_session_path %></li>
        <li><%= link_to "Sign Up", new_user_registration_path %> </li> 
       
      <% end %>
    
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoodGiving</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="initial-scale = 1.0,maximum-scale = 1.0" />
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Merriweather&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="shortcut icon" href="logo.jpg"/>
  </head>

    

  <body>
  
    <%=render 'layouts/navigation'%>
    <%= yield %>
     <%=render 'layouts/footer'%>
  

    
  </body>
</html>

app/views/pages/home.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Counter-Up/1.0.0/jquery.counterup.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/jquery.waypoints.js"></script>

<div class="home">
  <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">

    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-example-generic" data-slide-to="1"></li>
      <li data-target="#carousel-example-generic" data-slide-to="2"></li>
      <li data-target="#carousel-example-generic" data-slide-to="3"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <%= image_tag "home-bg-1.jpg", alt: "home-bg-1.jpg", class:"home_bg" %>
        <div class="carousel-caption">
          <span class="top-text">Help The</span> <br>
          <span><span class="yellow">Children</span> In Need</span>
          <p>Even the smallest of donations can help change a life</p>
          <%= link_to 'View More', charity_path(id:"12"), class: "donate-button1" %>
        </div>
      </div>
      <div class="item">
        <%= image_tag "home-bg-3.jpg", alt: "home-bg-4.jpg", class:"home_bg" %>
        <div class="carousel-caption">
        <span class="top-text">Help The</span> <br>
          <span><span class="yellow">Elephants</span> In Need</span>
          <p>Even the smallest of donations can help change a life</p>
           <%= link_to 'View More', charity_path(id:"20"), class: "donate-button1" %>
        </div>
      </div>
      <div class="item">
        <%= image_tag "home-bg-4.jpg", alt: "home-bg-2.jpg", class:"home_bg"%>
        <div class="carousel-caption">
        <span class="top-text">Help The</span> <br>
          <span><span class="yellow">Rhino</span> In Need</span>
          <p>Even the smallest of donations can help change a life</p>
           <%= link_to 'View More', charity_path(id:"11"), class: "donate-button1" %>
        </div>
      </div>
      <div class="item">
        <%= image_tag "home-bg-2.jpg", alt: "home-bg-3.jpg", class:"home_bg"%>
        <div class="carousel-caption">
        <span class="top-text">Help The</span> <br>
          <span><span class="yellow">Children</span> In Need</span>
          <p>Even the smallest of donations can help change a life</p>
           <%= link_to 'View More', charity_path(id:"16"), class: "donate-button1" %>
        </div>
      </div>
    
    </div>

  </div>


   <div class="number-counter">
     <div class="middle">
      <div class="counting-sec">
        <div class="inner-width">
        
          <div class="col">
            
            <div class="num">10</div>
            <h4>years</h4>
          </div>

          <div class="col">
           
            <div class="num">44,4957</div>
            <h4>dollars</h4>
          </div>

          <div class="col">
            
            <div class="num">56,638</div>
            <h4>donors</h4>
          </div>

          <div class="col">
            <div class="num">24,174</div>
            <h4>Proejcts</h4>
          </div>

          <div class="col">
            <div class="num">32</div>
            <h4>countries</h4>
          </div>
          <div class="col">
            <div class="num">68</div>
            <h4>organizations</h4>
          </div>
        </div>
      </div>
    </div>
  </div>
   


  <div class="aboutUs">
    <div class="container">

      <div class="title-infor">
        <h2>Who We Are</h2>
        <h3>GoodGiving connects nonprofits, donors, and companies in nearly every country around the world. We help local nonprofits access the funding, tools, training, and support they need to become more effective.</h3>
      </div>

      <div class="infor-box">
        <div class="container">
          <div class="row">
            <div class="col-md-4 mx-auto">
              <div class="box1">
                
              </div>

              <div class="box-infor">
                <div class="desc">
                  <p>Nonprofits around the world apply and join GlobalGiving to access more funding, to build new skills, and to make important connections.</p>
                </div>
                
                <%= link_to 'Volunteer', user_session_path,class:"signIn" %>
              </div>
              
            </div>
            <div class="col-md-4 mx-auto">
              <div class="box2">
              
              </div>
              <div class="box-infor">
                <div class="desc">
                 <p>People like you give what you can to your favorite projects; you feel great when you get updates about how your money is put to work by trusted organizations.</p>
                </div>
                <%= link_to 'Donor', user_session_path,class:"signIn" %>
              </div>
            
            </div>
            <div class="col-md-4 mx-auto box3">
              <div class="box3">
              
              </div>
              <div class="box-infor">
                <div class="desc">
                <p>Generous organizations and their employees further support high-impact projects, helping local communities thrive.</p>
                </div>
                <%= link_to 'Organization', user_session_path,class:"signIn" %>
              </div>
            
            </div>
          </div>
        </div> 
      </div>
      
    </div>
  </div>


  <div class="projects">
    <div class="row ">
      <div class="col-md-4  mx-auto clear-padding-col clear-padding-row">
        <div class="project-one clear-col">
            <h1>Today is the day to  <br>
            reach out and lend a  <br>
            helping hand</h1>
            <%= link_to 'View More', charity_path(id:"4"), class: "donate-button2" %>
        </div>
      </div>
      <div class="col-md-4  mx-auto clear-col">
      <div class="project-two">
            <h1>Even the smallest of<br> donations can help change a life</h1>
            <%= link_to 'View More', charity_path(id:"5"), class: "donate-button2" %>
        </div>
      
      </div>
      <div class="col-md-4  mx-auto clear-col">
        <div class="project-three">
            <h1>Become a volunteer. You’ll feel the <br>benefits instantly</h1>
            <%= link_to 'View More', charity_path(id:"13"), class: "donate-button2" %>
        </div>

      </div>
    </div>
  </div>




 


</div>



<script type="text/javascript">
    $(".num").counterUp({delay:10,time:8000});
  </script>